spring.application.name=findflix
server.port=2001
yts.api.base-url=https://yts.gg/api/v2/
yts.proxy.enabled=false
yts.proxy.host=127.0.0.1
yts.proxy.port=7890
yts.proxy.type=HTTP
spring.http.clients.connect-timeout=5s
spring.http.clients.read-timeout=20s
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId:-}] [%thread] %logger{36} - %msg%n
logging.level.com.FindFlix.findflix=INFO

